name: Android Environment Setup
runs:
  using: "composite"
  steps:
    - name: Free disk space
      uses: ./mobile-android-pipelines/actions/clean-runner-fast

    - name: Clean workspace
      uses: ./mobile-android-pipelines/actions/clean-workspace

    - name: Configure git User
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Setup GitHub Runner workflow
      uses: ./mobile-android-pipelines/actions/setup-runner
      with:
        gradle-cache-disabled: "false"
        jdk-version: "21"

    - name: Cache Homebrew packages
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/Library/Caches/Homebrew
          /home/linuxbrew/.linuxbrew/Cellar
          /home/linuxbrew/.linuxbrew/opt
          /home/linuxbrew/.linuxbrew/bin
          /home/linuxbrew/.linuxbrew/lib
        key: brew-${{ runner.os }}-${{ hashFiles('Brewfile') }}
        restore-keys: |
          brew-${{ runner.os }}-

    - name: Install homebrew packages
      shell: bash
      run: |
        brew bundle
