#!/usr/bin/env bash

# Installs the Android CLI if it's not in the PATH variable.
# Installs all skills referenced in the file provided in the first input parameter.
# If no file is provided, all skills are installed.

source "$(git rev-parse --show-toplevel)/scripts/env"

if command -v android > /dev/null; then
  echo "Android CLI is already installed. Installing skills..."
else
  echo "Android CLI not found on PATH. Installing..."

  OS="$(uname -s)"
  ARCHITECTURE="$(uname -m)"
  curl -fsSL "https://dl.google.com/android/cli/latest/${OS}_${ARCHITECTURE}/install.sh" | bash
fi

android skills add --all --project="${GIT_ROOT}" --agent=common
