#!/usr/bin/env bash
# Exit immediately if a simple command exits with a non-zero status
# see also: the 'set' command within the 'Shell Builtin Commands' section of `man bash`
set -o errexit

# Script for running all contract tests within the code base.
# Skips running the unit tests for the `release` build type.

# The `"${@}" appends additional input to the command, like so:
# `./scripts/test/unit --debug` -> adds `--debug` to the command.
./gradlew \
  :iso18013-6-tests:testReleaseUnitTest \
  "${@}"
