#!/usr/bin/env bash
# Exit immediately if a simple command exits with a non-zero status
# see also: the 'set' command within the 'Shell Builtin Commands' section of `man bash`
set -o errexit

# Script for enabling hardware acceleration on a ubuntu github workflow

# Get common environment variables
source "$(dirname "${0}")"/env

# Update apt repositories
sudo apt-get update

# Install required apt / snap packages for the project
xargs -a "${GIT_ROOT}"/.config/dependencies/aptPackages.txt sudo apt-get -y install
xargs -a "${GIT_ROOT}"/.config/dependencies/snapPackages.txt sudo snap install

# Update properties to allow hardware acceleration
# https://github.blog/changelog/2024-04-02-github-actions-hardware-accelerated-android-virtualization-now-available/
echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
sudo udevadm control --reload-rules
sudo udevadm trigger --name-match=kvm
