#!/usr/bin/env bash
# Exit immediately if a simple command exits with a non-zero status
# see also: the 'set' command within the 'Shell Builtin Commands' section of `man bash`
set -o errexit

if command -v cog; then
  cog -v get-version
else
  echo "0.0.1"
fi
