#!/usr/bin/env bash

source "$(git rev-parse --show-toplevel)/scripts/env"
"${GIT_ROOT}"/gradlew \
    lintDebug \
    detekt \
    spotlessCheck \
    "${@}" \
    --rerun-tasks \
    --stacktrace \
