#!/usr/bin/env bash

# Exit immediately if a simple command exits with a non-zero status
# see also: the 'set' command within the 'Shell Builtin Commands' section of `man bash`
set -o errexit

source "$(git rev-parse --show-toplevel)/scripts/env"
"${GIT_ROOT}"/gradlew \
    detekt \
    spotlessCheck \
    "${@}" \
    --rerun-tasks \
    --stacktrace \
