#!/usr/bin/env bash
# Exit immediately if a simple command exits with a non-zero status
# see also: the 'set' command within the 'Shell Builtin Commands' section of `man bash`
set -o errexit

SCRIPT_FOLDER=$(dirname "${0}")

# Run the various testing suites
"${SCRIPT_FOLDER}"/unit "${@}"
# "${SCRIPT_FOLDER}"/instrumentation "${@}" Android Tests need investigating, running with RoboElectric

# Combine test coverage data from the various testing suites
./gradlew combineDebugJacocoReports "${@}"
