#!/usr/bin/env bash
# Exit immediately if a simple command exits with a non-zero status
# see also: the 'set' command within the 'Shell Builtin Commands' section of `man bash`
set -o errexit

SCRIPT_FOLDER=$(dirname "${0}")

# Run the various testing suites
"${SCRIPT_FOLDER}"/unit/release "${@}"
"${SCRIPT_FOLDER}"/contract/release "${@}"
"${SCRIPT_FOLDER}"/instrumentation/release "${@}"
