name: "Linting"

on:
  push:
    branches:
      - main
  merge_group:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: linting-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  packages: read

jobs:
  conventional_commits:
    name: "Conventional commits"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/android-setup
        with:
          install-vale: 'false'

      - name: Verify Conventional commit standards against latest git tag
        run: cog check -l
        shell: bash

  prose_linting:
    name: "Prose"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/android-setup

      - name: Run vale prose linting
        run: ./scripts/lint/vale/run

  android_linting:
    name: "Android"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/android-setup
        with:
          install-vale: 'false'

      - name: Run linting associated with Android
        run: |
          ./scripts/lint/android

  kotlin_linting:
    name: "Kotlin"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/android-setup
        with:
          install-vale: 'false'

      - name: Run linting associated with Kotlin
        run: |
          ./scripts/lint/kotlin
