name: Release mobile-credential-sharing-android

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bump-version:
    name: "Bump semantic version"
    permissions:
      contents: write
      id-token: write
      packages: read
    secrets: inherit
    uses: ./.github/workflows/bump-version.yml
    with:
      # Empty to denote a 'production' release.
      pre-release-type: ''


  dependency-graph:
    name: "Submit gradle dependency graph"
    permissions:
      contents: write
      id-token: write
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/android-setup

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0


  linting:
    name: "Lint code base"
    uses: ./.github/workflows/linting.yml
    secrets: inherit


  publishing:
    if: ${{ jobs.bump-version.outputs.current-version != jobs.bump-version.outputs.new-version }}
    name: "Publish code base"
    needs: bump-version
    permissions:
      contents: write
      id-token: write
      packages: read
    secrets: inherit
    uses: ./.github/workflows/publishing.yml
    with:
      ref: ${{ jobs.bump-version.outputs.new-version }}
      version-code: ${{ jobs.bump-version.outputs.version-code }}


  testing:
    name: "Test code base"
    uses: ./.github/workflows/testing.yml
    secrets: inherit
