# Publishes the test app's Android Application Bundle (AAB) to the Google Play Store.
#
# Takes in a `ref` for checking out the code base.
# Takes in a `version-code` for Android fingerprinting purposes.
name: "Publish app to Google Play"

on:
  workflow_call:
    inputs:
      ref:
        description: |
          [Branch | Tag | SHA] of the code base to publish.
          Used as the reference when checking out the repository.
          
          If not specified, defaults to using the github ref as a replacement.
        required: false
        type: string

      semantic-version:
        description: |
          The semantic version of the code base to publish.

          If not specified, defaults to using the github ref as a replacement.
        required: false
        type: string

      version-code:
        description: "The test app's version code to use when publishing to google play"
        required: true
        type: string

concurrency:
  group: publish-to-google-play-${{ github.workflow }}-${{ inputs.ref || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish-to-google-play:
    name: "Publish test app to Google Play"
    permissions:
      contents: write
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.ref || github.ref }}
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0
          fetch-tags: 'true'

      - name: Setup
        uses: ./.github/actions/android-setup

      - name: Retrieve Secrets
        id: secrets
        uses: ./mobile-android-pipelines/actions/retrieve-secrets
        with:
          keystore-base64: ${{ secrets.KEYSTORE_BASE64 }}
          # No service account needed as we are using Workload Identity Federation
          google-service-account-json-base64: ""

      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        id: auth
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/deploy-credential-sharing-and/providers/github-actions
          service_account: deploy-credential-sharing-and@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Bundle Demo Release
        id: bundle
        uses: ./mobile-android-pipelines/actions/bundle-release-app
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          keystore-file-path: ${{ steps.secrets.outputs.keystore-file-path }}
          keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          keystore-key-alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          keystore-key-password: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          version-code: ${{ inputs.version-code }}
          version-name: ${{ inputs.semantic-version || github.ref }}

      - name: Publish to Play Store
        uses: ./mobile-android-pipelines/actions/publish-to-play-store
        with:
          aab-paths: ${{ steps.bundle.outputs.aab-paths }}
          package-name: 'uk.gov.onelogin.sharing.testapp'
          google-service-account-json: ${{ steps.auth.outputs.credentials_file_path }}
          track: 'internal'

      - name: Clean workspace
        uses: ./mobile-android-pipelines/actions/clean-workspace
