name: "Pull Request workflow"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  packages: read

jobs:
  linting:
    name: "Linting"
    uses: ./.github/workflows/linting.yml

  testing:
    name: "Test suites"
    uses: ./.github/workflows/testing.yml
