name: "Pull Request workflow"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  packages: read

jobs:
  linting:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Linting workflow
        uses: ./.github/workflows/linting.yml

  testing:
    name: "Test suites"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Testing workflow
        uses: ./.github/workflows/testing.yml
